version: "3.9"

services:

  api:
    container_name: "printscript_service"
    build:
      context: .
    ports:
      - "8084:8084"
    environment:
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
      REDIS_HOST: redis # O local host??
      REDIS_PORT: 6379

  redis:
    container_name: "redis-stream"
    image: redis:6-alpine
    ports:
      - "6379:6379"
