version: "3.9"

services:

  api:
    container_name: "printscript_service"
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
