# redis host and port parameters
server:
  port: 8083

spring:
  data:
    redis:
      host: redis
      port: 6379
  application:
    name: printscript-service

# streamKeys to be used by producers
# claves usadas para acceder a los diferentes streams.
redis:
  stream:
    linter-request-key: "linter-request-key"
    linter-response-key: "linter-response-key"

  # groupIds to be used by consumers
  # facilita que múltiples consumidores puedan leer desde el mismo stream sin procesar los mismos mensajes más de una vez.
  # Si están agrupados se puede coordinar la lectura
  groups:
    lint: "lint-group"
